image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.1.0"

before_script:
  - env
  - ls -lah
  - pwd
  - env
  - cat /etc/os-release

stages:
  - build
  - test
  - deploy
  - verify
  - cleanup

build:
  stage: build
  environment: prd
  script:
    - pwd
    - export SYS_HELM_NAMESPACE_SUFFIX="cid${CI_PIPELINE_ID}"
    - export SYS_K8S_NAMESPACE="env-${SYS_HELM_NAMESPACE_SUFFIX}"
    - git clone https://gitlab.com/sysf/kubernetes/cluster/sysf.git /tmp/sysf

    - cd /tmp/sysf
    - kubectl create namespace "${SYS_K8S_NAMESPACE}"
    - kubectl config set-context --current --namespace="${SYS_K8S_NAMESPACE}"
    - "kubectl get secret ssh-config --namespace=default -o yaml | sed \"s/namespace: default/namespace: $SYS_K8S_NAMESPACE/\" | kubectl apply --namespace=$SYS_K8S_NAMESPACE -f - || true"
    - "kubectl get secret tls-sys --namespace=default -o yaml | sed \"s/namespace: default/namespace: $SYS_K8S_NAMESPACE/\" | kubectl apply --namespace=$SYS_K8S_NAMESPACE -f - || true"
    - "kubectl get secret mariadb --namespace=default -o yaml | sed \"s/namespace: default/namespace: $SYS_K8S_NAMESPACE/\" | kubectl apply --namespace=$SYS_K8S_NAMESPACE -f - || true"
    - helmfile --environment=cid apply
    - while [[ $(kubectl get pods -l app=web-nginx-php-fpm -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done
    - POD_EXEC=$(kubectl get pod -l app=web-nginx-php-fpm -o jsonpath="{.items[0].metadata.name}")
    - kubectl cp "${CI_PROJECT_DIR}" "${POD_EXEC}:/app" -c php-fpm
    - alias exec_cid="kubectl exec ${POD_EXEC} -c php-fpm -- bash -c"
    - exec_cid "mv /app/sysf/* /app"

    - exec_cid "composer install"
    - exec_cid "/app/vendor/bin/blt artifact:deploy --branch=master-build --no-interaction"

    - helmfile --environment=cid destroy
    - kubectl delete pods -n "${SYS_K8S_NAMESPACE}" --all --force
    - kubectl delete pvc -n "${SYS_K8S_NAMESPACE}" --all --force
    - kubectl delete ns "${SYS_K8S_NAMESPACE}" --force

# test-coding-standard:
#   stage: test
#   environment: cid2
#   script:
#     - 'echo "Test: coding standard..."'
# #  only:
# #    - merge_requests

# test-workflow-standard:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: workflow standard..."'
# #  only:
# #    - merge_requests

# test-security:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: security..."'
# #  only:
# #    - merge_requests

# test-licensing:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: licensing..."'
# #  only:
# #    - merge_requests

# test-visual-regression:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: visual regression..."'
# #  only:
# #    - merge_requests

# test-behavioral:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: behavioral..."'
# #  only:
# #    - merge_requests

# test-performance:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: performance..."'
# #  only:
# #    - merge_requests

# deploy-code:
#   stage: deploy
#   environment: cid1
#   script:
#     - 'echo "Deploying build artifact..."'
# #    - composer install --ignore-platform-reqs
# #    - vendor/bin/blt artifact:deploy --branch=master-build --no-interaction

# deploy:
#   stage: deploy
#   environment: dev
#   when: manual
#   script:
#     - 'echo "Deploying build artifact..."'
# #    - composer install --ignore-platform-reqs
# #    - vendor/bin/blt artifact:deploy --branch=master-build --no-interaction

# deploy_stg:
#   stage: deploy
#   environment: stg
#   when: manual
#   script:
#     - 'echo "Deploying build artifact..."'
# #    - composer install --ignore-platform-reqs
# #    - vendor/bin/blt artifact:deploy --branch=master-build --no-interaction

# deploy_prd:
#   stage: deploy
#   environment: prd
#   when: manual
#   script:
#     - 'echo "Deploying build artifact..."'
# #    - composer install --ignore-platform-reqs
# #    - vendor/bin/blt artifact:deploy --branch=master-build --no-interaction

# verify:
#   stage: verify
#   environment: cid1
#   script:
#     - 'echo "Verifying deploy..."'
# #  only:
# #    - merge_requests

# cleanup:
#   stage: cleanup
#   environment: prd
#   dependencies:
#     - build
#   script:
#     - 'echo "Cleanup..."'
#     - ls -lah
#     - cd /tmp/sysf
#     - export SYS_HELM_NAMESPACE_SUFFIX="cid${CI_PIPELINE_ID}"
#     - export SYS_K8S_NAMESPACE="env-${SYS_HELM_NAMESPACE_SUFFIX}"
#     - helmfile --environment=cid destroy
#     - kubectl delete pods -n "${SYS_K8S_NAMESPACE}" --all --force
#     - kubectl delete pvc -n "${SYS_K8S_NAMESPACE}" --all --force
#     - kubectl delete ns "${SYS_K8S_NAMESPACE}" --force
