image:
  name: registry.gitlab.com/sysf/docker/image/php-fpm:latest

before_script:
  - env
  - rm -rf /app
  - ln -s "${CI_PROJECT_DIR}" /app

cache:
  key: "$CI_COMMIT_REF_SLUG"
  policy: pull-push
  paths:
    - files-private/cache

stages:
  - init
  - build
  - test
  - deploy
  - verify
  - cleanup

init:
  stage: init
  environment: prd
  script:
    - 'echo "Initializing kubernetes environment..."'
    - mkdir -p files-private/cache

build:
  stage: build
  environment: prd
  script:
    - 'echo "Building source repo..."'
    - composer install
    - ./vendor/bin/blt artifact:deploy --branch=master-build --no-interaction

test-coding-standard:
  stage: test
  environment: prd/1
  script:
    - 'echo "Test: coding standard..."'

test-workflow-standard:
  stage: test
  environment: prd/2
  script:
    - 'echo "Test: workflow standard..."'

test-security:
  stage: test
  environment: prd/3
  script:
    - 'echo "Test: security..."'

test-licensing:
  stage: test
  environment: prd/4
  script:
    - 'echo "Test: licensing..."'

test-visual-regression:
  stage: test
  environment: prd/5
  script:
    - 'echo "Test: visual regression..."'

test-behavioral:
  stage: test
  environment: prd/6
  script:
    - 'echo "Test: behavioral..."'

test-performance:
  stage: test
  environment: prd/7
  script:
    - 'echo "Test: performance..."'

deploy:
  stage: deploy
  environment: prd
  script:
    - 'echo "Deploying build artifact..."'

verify:
  stage: verify
  environment: prd
  dependencies:
    - deploy
  script:
    - 'echo "Verifying deploy..."'

cleanup:
  stage: cleanup
  environment: prd
  when: always
  script:
    - rm -rf files-private/cache/sysf
