image: "registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:v1.1.0"

before_script:
  - env
  - ls -lah
  - pwd
  - env
  - cat /etc/os-release

stages:
  - build
  - test
  - deploy
  - verify
  - cleanup

build:
  stage: build
  environment: prd
  script:
   - helmfile --environment=cid apply
    - ls -lah /tmp

# test-coding-standard:
#   stage: test
#   environment: cid2
#   script:
#     - 'echo "Test: coding standard..."'
# #  only:
# #    - merge_requests

# test-workflow-standard:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: workflow standard..."'
# #  only:
# #    - merge_requests

# test-security:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: security..."'
# #  only:
# #    - merge_requests

# test-licensing:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: licensing..."'
# #  only:
# #    - merge_requests

# test-visual-regression:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: visual regression..."'
# #  only:
# #    - merge_requests

# test-behavioral:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: behavioral..."'
# #  only:
# #    - merge_requests

# test-performance:
#   stage: test
#   environment: cid1
#   script:
#     - 'echo "Test: performance..."'
# #  only:
# #    - merge_requests

# deploy-code:
#   stage: deploy
#   environment: cid1
#   script:
#     - 'echo "Deploying build artifact..."'
# #    - composer install --ignore-platform-reqs
# #    - vendor/bin/blt artifact:deploy --branch=master-build --no-interaction

# deploy:
#   stage: deploy
#   environment: dev
#   when: manual
#   script:
#     - 'echo "Deploying build artifact..."'
# #    - composer install --ignore-platform-reqs
# #    - vendor/bin/blt artifact:deploy --branch=master-build --no-interaction

# deploy_stg:
#   stage: deploy
#   environment: stg
#   when: manual
#   script:
#     - 'echo "Deploying build artifact..."'
# #    - composer install --ignore-platform-reqs
# #    - vendor/bin/blt artifact:deploy --branch=master-build --no-interaction

# deploy_prd:
#   stage: deploy
#   environment: prd
#   when: manual
#   script:
#     - 'echo "Deploying build artifact..."'
# #    - composer install --ignore-platform-reqs
# #    - vendor/bin/blt artifact:deploy --branch=master-build --no-interaction

# verify:
#   stage: verify
#   environment: cid1
#   script:
#     - 'echo "Verifying deploy..."'
# #  only:
# #    - merge_requests

# cleanup:
#   stage: cleanup
#   environment: prd
#   dependencies:
#     - build
#   script:
#     - 'echo "Cleanup..."'
#     - ls -lah
#     - cd /tmp/sc
#     - export SYS_HELM_NAMESPACE_SUFFIX="cid-${CI_PIPELINE_ID}"
#     - export SYS_K8S_NAMESPACE="env-${SYS_HELM_NAMESPACE_SUFFIX}"
#     - helmfile --environment=cid destroy
#     - kubectl delete pods -n "${SYS_K8S_NAMESPACE}" --all --force
#     - kubectl delete pvc -n "${SYS_K8S_NAMESPACE}" --all --force
#     - kubectl delete ns "${SYS_K8S_NAMESPACE}" --force
